version: '3.7'

services:
  coverage:
    image: bobcat-linker
    build:
      context: .
      cache_from:
        - bobcat-linker
        - $IMAGES_DOMAIN/bobcat-linker
    command: yarn test-and-report
    environment:
      COVERALLS_REPO_TOKEN: 

  deploy:
    image: bobcat-linker
    build:
      context: .
      cache_from:
        - bobcat-linker
        - $IMAGES_DOMAIN/bobcat-linker
    command: yarn deploy --stage=${STAGE} --region=${REGION}
    environment:
      LAMBDA_ROLE:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      REGION:
      STAGE:
      REST_API_ID:
      REST_API_ROOT_RESOURCE_ID:
      REST_API_NAMESPACE_RESOURCE_ID:
      S3_BUCKET:
      # LAMBDA SECRETS
      WORLDCAT_API_KEY:

  terraform_deploy:
    image: quay.io/nyulibraries/web-lambdas-terraform:master
    command: ["terraform", "apply", "-auto-approve"]
    # env_file: dev.env
    env_file: terraform.env
    environment:
      - BACKEND_CONFIG=backend-dev.env
      - TF_VAR_lambda_function_name=bobcat-linker
      - TF_VAR_lambda_handler=handler.persistent
      - TF_VAR_lambda_runtime=nodejs12.x
      - TF_VAR_lambda_method=GET
      - TF_VAR_lambda_memory_limit=1024
      - TF_VAR_environment_variables='{"WORLDCAT_API_KEY":"${WORLDCAT_API_KEY}"}'

  build_lambda:
    image: bobcat-linker-build
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        production: "true"
    command: sh -c 'mkdir dist; cat .lambdafiles | xargs zip -r -9 -q ./dist/bobcat-linker.zip'
    labels:
      - 'nyulibraries.app=bobcat-linker'
    # volumes:
    #   - ./dist:/app/dist