test:
  build: .
  command: yarn coveralls
  environment:
    COVERALLS_REPO_TOKEN:

deploy:
  build: .
  command: yarn deploy
  environment:
    LAMBDA_ROLE:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    STAGE:
