version: '3.2'
services:
  test:
    image: bobcat-linker:latest
    build:
      context: .
    command: yarn coveralls
    environment:
      COVERALLS_REPO_TOKEN:

  deploy:
    image: bobcat-linker:latest
    build:
      context: .
    command: yarn deploy
    environment:
      LAMBDA_ROLE:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      STAGE:
      REGION:
      WORLDCAT_API_KEY:
      REST_API_ID: