test:
  build: .
  command: yarn test

deploy:
  build: .
  command: yarn deploy --stage ${STAGE}
  environment:
    - LAMBDA_ROLE=$LAMBDA_ROLE
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
