version: '3.2'
services:
  test:
    image: bobcat-linker
    build:
      context: .
      cache_from:
        - bobcat-linker
        - $IMAGES_DOMAIN/bobcat-linker
    command: yarn coveralls
    environment:
      COVERALLS_REPO_TOKEN:

  deploy:
    image: bobcat-linker
    build:
      context: .
      cache_from:
        - bobcat-linker
        - $IMAGES_DOMAIN/bobcat-linker
    command: yarn deploy --stage=${STAGE} --region=${REGION}
    environment:
      LAMBDA_ROLE: ${LAMBDA_ROLE?"Must specify LAMBDA_ROLE"}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID?"Must specify AWS_ACCESS_KEY_ID"}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY?"Must specify AWS_SECRET_ACCESS_KEY"}
      REGION: ${REGION?"Must specify REGION"}
      STAGE: ${STAGE?"Must specify STAGE"}
      WORLDCAT_API_KEY: ${WORLDCAT_API_KEY?"Must specify WORLDCAT_API_KEY"}
      REST_API_ID: ${REST_API_ID?"Must specify REST_API_ID"}
      REST_API_ROOT_RESOURCE_ID: ${REST_API_ROOT_RESOURCE_ID?"Must specify REST_API_ROOT_RESOURCE_ID"}
      REST_API_NAMESPACE_RESOURCE_ID: ${REST_API_NAMESPACE_RESOURCE_ID?"Must specify REST_API_NAMESPACE_RESOURCE_ID"}
      S3_BUCKET: ${S3_BUCKET?"Must specify S3_BUCKET"}