version: '3.7'

x-default-tf-vars: &default_tf_vars
  AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
  TF_VAR_lambda_memory_limit=${TF_VAR_lambda_memory_limit}
  TF_VAR_lambda_exec_arn=${TF_VAR_lambda_exec_arn}
  TF_VAR_apigw_id=${TF_VAR_apigw_id}
  TF_VAR_apigw_root_resource_id=${TF_VAR_apigw_root_resource_id}
  TF_VAR_apigw_execution_arn=${TF_VAR_apigw_execution_arn}
  TF_VAR_lambda_s3_bucket=${TF_VAR_lambda_s3_bucket}
  TF_VAR_aws_username=${TF_VAR_aws_username}
  TF_VAR_apigw_stage=${TF_VAR_apigw_stage}
  TF_VAR_lambda_version=${TF_VAR_lambda_version}
  TF_VAR_environment_variables=${TF_VAR_environment_variables}

services:
  coverage:
    image: bobcat-linker
    build:
      context: .
      cache_from:
        - bobcat-linker
        - $IMAGES_DOMAIN/bobcat-linker
    command: yarn test-and-report
    environment:
      COVERALLS_REPO_TOKEN: 

  deploy:
    image: bobcat-linker
    build:
      context: .
      cache_from:
        - bobcat-linker
        - $IMAGES_DOMAIN/bobcat-linker
    command: yarn deploy --stage=${STAGE} --region=${REGION}
    environment:
      LAMBDA_ROLE:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      REGION:
      STAGE:
      REST_API_ID:
      REST_API_ROOT_RESOURCE_ID:
      REST_API_NAMESPACE_RESOURCE_ID:
      S3_BUCKET:
      # LAMBDA SECRETS
      WORLDCAT_API_KEY:

  tf:
    image: web-lambdas-deploy
    build:
      context: ./terraform
    command: ["terraform", "apply", "-auto-approve"]
    # env_file: dev.env
    environment:
      - BACKEND_CONFIG=dev.backend
      - TF_VAR_lambda_function_name=bobcat-linker
      - TF_VAR_lambda_handler=handler.persistent
      - TF_VAR_lambda_runtime=nodejs12.x
      - TF_VAR_lambda_method=GET

  build_lambda:
    image: bobcat-linker-build
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        production: "true"
    command: sh -c 'cat .lambdafiles | xargs zip -r -9 -q ./dist/bobcat-linker.zip'
    labels:
      - 'nyulibraries.app=bobcat-linker'
    volumes:
      - ./dist:/app/dist