version: '3.7'

x-environment: &x-environment
  BACKEND_BUCKET: 
  BACKEND_REGION: 
  BACKEND_DYNAMODB_TABLE: 
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_DEFAULT_REGION: 
  TF_VAR_lambda_exec_arn: 
  TF_VAR_apigw_id: 
  TF_VAR_apigw_root_resource_id: 
  TF_VAR_apigw_execution_arn: 
  TF_VAR_lambda_s3_bucket: 
  TF_VAR_aws_username: 
  TF_VAR_apigw_stage:
  TF_VAR_lambda_version:
  TF_VAR_environment_variables:
  WORLDCAT_API_KEY:
  LAMBDA_FN:
  S3_BUCKET:

services:
  test:
    image: bobcat-linker
    build:
      context: .
      dockerfile: Dockerfile.node
      cache_from:
        - bobcat-linker
        - quay.io/nyulibraries/bobcat-linker
    command: yarn test-and-report
    environment:
      COVERALLS_REPO_TOKEN: 
    # volumes:
    #   - .:/app

  fn_create:
    image: bobcat-linker-create
    build:
      context: .
      dockerfile: Dockerfile.deploy
    environment:
      <<: *x-environment
    entrypoint: ["./create.sh"]
  
  fn_destroy:
    image: bobcat-linker-destroy
    build:
      context: .
      dockerfile: Dockerfile.deploy
    environment:
      <<: *x-environment
    entrypoint: ["./destroy.sh"]

  build_lambda:
    image: bobcat-linker-build
    build: 
      context: .
      dockerfile: Dockerfile.node
      args:
        production: "true"
    command: sh -c 'mkdir dist; cat .lambdafiles | xargs zip -r -9 -q ./dist/bobcat-linker.zip'
    labels:
      - 'nyulibraries.app=bobcat-linker'

  clear_old_builds:
    image: bobcat-linker-clear-builds
    build:
      context: .
      dockerfile: Dockerfile.deploy
    entrypoint: ["sh"]
    command: ["./clear_old_builds.sh"]
    environment:
      <<: *x-environment