FROM quay.io/nyulibraries/web-lambdas-terraform:bug_fixing_dynamic_envars

RUN apk update && \
    apk upgrade && \
    apk add --no-cache gettext curl yq~=4

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
        unzip awscliv2.zip && \
        ./aws/install

COPY .tf_env_vars deploy.yml ./
