service: web-bobcat-linker
provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs8.10
  role: ${env:LAMBDA_ROLE}
  stage: ${opt:stage, 'dev'}
  apiName: web-lambdas
  environment:
    WORLDCAT_API_KEY: ${env:WORLDCAT_API_KEY}
  deploymentBucket:
    name: nyulibraries-${self:service}-${opt:stage, 'dev'}
  apiGateway:
    restApiId: ${env:REST_API_ID}
    restApiRootResourceId: ${env:REST_API_ROOT_RESOURCE_ID}
    restApiResources:
      '/bobcat-linker': ${env:REST_API_NAMESPACE_RESOURCE_ID} # ID for '/bobcat-linker' resource

package:
  include:
    - handler.js
    - common/**
    - config/**

functions:
  persistent:
    name: ${self:service}-${opt:stage, 'dev'}-persistent
    events:
      - http:
          method: get
          path: bobcat-linker/persistent
    handler: handler.persistent
    memorySize: 1024

# settings below necessary for using dev/prod on the same api gateway
resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: web-lambdas
    ApiGatewayDeploymentDev:
      Type: AWS::ApiGateway::Deployment
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi
        Description: 'Development stage deployment'
    ApiGatewayDeploymentProd:
      Type: AWS::ApiGateway::Deployment
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi
        Description: 'Production stage Deployment'
    ApiGatewayStageDev:
        Type: 'AWS::ApiGateway::Stage'
        Properties:
          StageName: dev
          Description: Dev Stage
          RestApiId:
            Ref: ApiGatewayRestApi
          DeploymentId:
            Ref: ApiGatewayDeploymentDev
          Variables:
            "Stage": "dev"
    ApiGatewayStageProd:
        Type: 'AWS::ApiGateway::Stage'
        Properties:
          StageName: prod
          Description: Prod Stage
          RestApiId:
            Ref: ApiGatewayRestApi
          DeploymentId:
            Ref: ApiGatewayDeploymentProd
          Variables:
            "Stage": "prod"