service: bobcat-linker
provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  role: "${env:LAMBDA_ROLE}"
  stage: "${env:STAGE}"
  environment:
    WORLDCAT_API_KEY: "${env:WORLDCAT_API_KEY}"

package:
  include:
    - handler.js
    - common/**
    - config/**

functions:
  persistent:
    name: web-${self:service}-persistent-${self:provider.stage}
    events:
      - http:
          method: get
          path: persistent
    handler: handler.persistent
    memorySize: 1024

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        Name: web-"${self:service}-${self:provider.stage}"
