service: web-lambdas-bobcat-linker
provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs8.10
  role: ${env:LAMBDA_ROLE}
  apiName: web-lambdas-${opt:stage, 'dev'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${env:S3_BUCKET}
  apiGateway:
    restApiId: ${env:REST_API_ID}
    restApiRootResourceId: ${env:REST_API_ROOT_RESOURCE_ID}
    restApiResources:
      '/bobcat-linker': ${env:REST_API_NAMESPACE_RESOURCE_ID} # ID for '/bobcat-linker' resource
  environment:
    WORLDCAT_API_KEY: ${env:WORLDCAT_API_KEY}

package:
  include:
    - handler.js
    - common/**
    - config/**
  exclude:
    - docker-compose*
    - Dockerfile*

functions:
  persistent:
    name: ${self:service}-persistent-${opt:stage, 'dev'}
    events:
      - http:
          method: get
          path: bobcat-linker
    handler: handler.persistent
    memorySize: 1024