# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - /tmp/node_modules

  test:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - run:
          name: Test
          command: docker-compose run test yarn test

  deploy-dev:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - run:
          name: Setup serverless configuration
          command: |
            export LAMBDA_ROLE="arn:aws:iam::168375318165:role/AWSLambdaBasicExecutionRole"
            yarn serverless config credentials --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY} --profile circle-ci-dev -o
      - run:
          name: Deploy to AWS development server with serverless
          command: yarn deploy --stage dev --conceal

  deploy-prod:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - run:
          name: Setup serverless configuration
          command: |
            export LAMBDA_ROLE="arn:aws:iam::168375318165:role/AWSLambdaBasicExecutionRole"
            yarn serverless config credentials --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY} --profile circle-ci-prod -o

      - run:
          name: Deploy to AWS production server with serverless
          command: yarn deploy --stage prod --conceal

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-dev:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - test
          filters:
            branches:
              only: development
