# Aliases
docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.3-dc-1.23.2-0
  working_directory: ~/app

auth_quay: &auth_quay
  run:
    name: Docker login
    command: docker login quay.io -u "$QUAY_USERNAME" --password "$QUAY_PASSWORD"

pull: &pull
  run:
    name: Pull docker images
    command: ./scripts/pull_docker.sh || exit 0

push: &push
  run:
    name: Push docker images
    command: ./scripts/push_docker.sh

build: &build
  run:
    name: Build images
    command: docker-compose build

test: &test
  run:
    name: Test
    command: docker-compose run coverage

set-bobcat-dev-env: &set-bobcat-dev-env
  run: 
    name: Set Bobcat URL for dev
    command: sed -i 's/bobcat\.library/bobcatdev\.library/g' config/baseUrls.json

set-env-stage-dev: &set-env-stage-dev
  run:
    name: Use development stage environment variables in awsdev account
    command: |
      echo 'export STAGE="dev"' >> $BASH_ENV
      echo 'export REST_API_ID="$REST_API_ID_DEV"' >> $BASH_ENV
      echo 'export REST_API_ROOT_RESOURCE_ID="$REST_API_ROOT_RESOURCE_ID_DEV"' >> $BASH_ENV


set-env-stage-prod: &set-env-stage-prod
  run:
    name: Use production stage environment variables in awsprod account
    command: |
      echo 'export STAGE="prod"' >> $BASH_ENV
      echo 'export REST_API_ID="$REST_API_ID_PROD"' >> $BASH_ENV
      echo 'export REST_API_ROOT_RESOURCE_ID="$REST_API_ROOT_RESOURCE_ID_PROD"' >> $BASH_ENV

aws-deploy: &aws-deploy
  run:
    name: Deploy via serverless to AWS account
    command: docker-compose run deploy

version: 2
jobs:
  deploy-staging-awsdev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - <<: *auth_quay
      - <<: *pull
      - <<: *set-bobcat-dev-env
      - <<: *build
      - <<: *push
      - <<: *set-env-stage-dev
      - <<: *aws-deploy

  deploy-staging-awsprod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - <<: *auth_quay
      - <<: *pull
      - <<: *set-bobcat-dev-env
      - <<: *build
      - <<: *push
      - <<: *set-env-stage-dev
      - <<: *aws-deploy

  deploy-production-awsprod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - <<: *auth_quay
      - <<: *pull
      - <<: *build
      - <<: *push
      - <<: *set-env-stage-prod
      - <<: *aws-deploy

  test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - <<: *auth_quay
      - <<: *pull
      - <<: *build
      - <<: *push
      - <<: *test

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy-staging-awsdev:
          context: web-lambdas-aws-nyulitsdev
          filters:
            branches:
              ignore: master
          requires:
            - test
      - deploy-staging-awsprod:
          context: web-lambdas-aws-nyulits
          filters:
            branches:
              ignore: master
          requires:
            - test
      - deploy-production-awsprod:
          context: web-lambdas-aws-nyulits
          filters:
            branches:
              only: master
          requires:
            - test
