# Aliases
docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.3-dc-1.23.2-0
  working_directory: ~/app

auth_quay: &auth_quay
  run:
    name: Docker login
    command: docker login quay.io -u "$QUAY_USERNAME" --password "$QUAY_PASSWORD"

pull: &pull
  run:
    name: Pull docker images
    command: ./scripts/pull_docker.sh || exit 0

push: &push
  run:
    name: Push docker images
    command: ./scripts/push_docker.sh

build: &build
  run:
    name: Build images
    command: docker-compose build

test: &test
  run:
    name: Test
    command: docker-compose run coverage

set-bobcat-dev-env: &set-bobcat-dev-env
  run: 
    name: Set Bobcat URL for dev
    command: sed -i 's/bobcat\.library/bobcatdev\.library/g' config/baseUrls.json

# To retire after lambda reworking
set-env-stage-dev: &set-env-stage-dev
  run:
    name: Use development stage environment variables in awsdev account
    command: |
      echo 'export STAGE="dev"' >> $BASH_ENV
      echo 'export REST_API_ID="$REST_API_ID_DEV"' >> $BASH_ENV
      echo 'export REST_API_ROOT_RESOURCE_ID="$REST_API_ROOT_RESOURCE_ID_DEV"' >> $BASH_ENV

# To retire after lambda reworking
set-env-stage-prod: &set-env-stage-prod
  run:
    name: Use production stage environment variables in awsprod account
    command: |
      echo 'export STAGE="prod"' >> $BASH_ENV
      echo 'export REST_API_ID="$REST_API_ID_PROD"' >> $BASH_ENV
      echo 'export REST_API_ROOT_RESOURCE_ID="$REST_API_ROOT_RESOURCE_ID_PROD"' >> $BASH_ENV

# To retire after lambda reworking
aws-deploy: &aws-deploy
  run:
    name: Deploy via serverless to AWS account
    command: docker-compose run deploy

s3_deploy: &s3_deploy
  aws-s3/sync:
    from: dist
    to: 's3://${TF_VAR_lambda_s3_bucket}/bobcat-linker/${CIRCLE_SHA1}'
    aws-access-key-id: AWS_ACCESS_KEY_ID
    aws-secret-access-key: AWS_SECRET_ACCESS_KEY
    arguments: |
      --exclude "*" \
      --include "bobcat-linker.zip" \
      --delete
    overwrite: true

zip: &zip
  run:
    name: Zip Lambda files
    command: docker-compose run build_lambda

get_lambda_zip: &get_lambda_zip
  run:
    name: Retrieve zipped lambda from container
    command: |
      docker cp $(docker ps -aq --filter 'label=nyulibraries.app=bobcat-linker'):/app/dist .

terraform_deploy: &terraform_deploy
  run:
    name: Deploy the Lambda to AWS via Terraform
    command: |
      TF_VAR_lambda_version=${CIRCLE_SHA1}
      TF_VAR_environment_variables='{"WORLDCAT_API_KEY":"${WORLDCAT_API_KEY}"}'
      docker-compose run terraform_deploy

version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  # Replacement Lambda logic
  build-lambda:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - <<: *set-bobcat-dev-env
      - <<: *build
      - <<: *zip
      - <<: *get_lambda_zip
      - <<: *s3_deploy
  
  # Replacement Lambda logic
  deploy-lambda:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - <<: *auth_quay
      - <<: *terraform_deploy

  # To retire after lambda reworking
  deploy-staging-awsdev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - <<: *auth_quay
      - <<: *pull
      - <<: *set-bobcat-dev-env
      - <<: *build
      - <<: *push
      - <<: *set-env-stage-dev
      - <<: *aws-deploy

  # To retire after lambda reworking
  deploy-staging-awsprod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - <<: *auth_quay
      - <<: *pull
      - <<: *set-bobcat-dev-env
      - <<: *build
      - <<: *push
      - <<: *set-env-stage-dev
      - <<: *aws-deploy

  # To retire after lambda reworking
  deploy-production-awsprod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - <<: *auth_quay
      - <<: *pull
      - <<: *build
      - <<: *push
      - <<: *set-env-stage-prod
      - <<: *aws-deploy

  test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - <<: *auth_quay
      - <<: *pull
      - <<: *build
      - <<: *push
      - <<: *test

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - build-lambda:
          context: web-lambdas-api-gateway-dev
          filters:
            branches:
              ignore: master
          requires:
            - test
      - deploy-lambda:
          context: web-lambdas-api-gateway-dev
          filters:
            branches:
              ignore: master
          requires:
            - build-lambda
      - deploy-staging-awsdev:
          context: web-lambdas-aws-nyulitsdev
          filters:
            branches:
              ignore: master
          requires:
            - test
      - deploy-staging-awsprod:
          context: web-lambdas-aws-nyulits
          filters:
            branches:
              ignore: master
          requires:
            - test
      - deploy-production-awsprod:
          context: web-lambdas-aws-nyulits
          filters:
            branches:
              only: master
          requires:
            - test
