# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-and-test:
    docker:
      - image: docker:17.11.0-ce
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup docker-compose dependency
          command: |
              apk add --no-cache python3
              pip3 install docker-compose
      - run:
          name: Test
          command: docker-compose run test yarn test

  deploy-dev:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run:
          name: Setup npm dependencies
          command: yarn install
      - run:
          name: Setup env
          command: export LAMBDA_ROLE=LAMBDA_ROLE_DEV
      - run:
          name: Setup serverless credentials
          command: yarn serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID_DEV --secret $AWS_SECRET_ACCESS_KEY_DEV --profile circle-ci-dev
      - run:
          name: Deploy to AWS development server with serverless
          command: yarn deploy --stage dev --aws-profile circle-ci-dev --conceal

  deploy-prod:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run:
          name: Setup serverless configuration
          command: |
            export LAMBDA_ROLE=$LAMBDA_ROLE_PROD
            yarn install
            yarn serverless config credentials \
              --provider aws \
              --key $AWS_ACCESS_KEY_ID_PROD --secret $AWS_SECRET_ACCESS_KEY_PROD \
              --profile circle-ci-prod

      - run:
          name: Deploy to AWS production server with serverless
          command: yarn deploy --stage prod --aws-profile circle-ci-prod --conceal

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - deploy-dev:
          requires:
            - build-and-test
          filters:
            branches:
              only: development
      - deploy-prod:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
