# Aliases
docker-defaults: &docker-defaults
  docker:
    - image: docker:17.11.0-ce
  working_directory: ~/app

dc-setup: &dc-setup
  run:
      name: Setup docker-compose dependency
      command: |
        apk add --no-cache python3
        pip3 install docker-compose

version: 2
jobs:
  build-and-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *dc-setup
      - run:
          name: Test
          command: docker-compose run test

  deploy-dev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *dc-setup
      - run:
          name: Deploy via serverless to dev
          command: |
            export LAMBDA_ROLE=$LAMBDA_ROLE_DEV
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV
            export STAGE=dev
            docker-compose run deploy

  deploy-prod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *dc-setup
      - run:
          name: Deploy via serverless to prod
          command: |
            export LAMBDA_ROLE=$LAMBDA_ROLE_PROD
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD
            export STAGE=prod
            docker-compose run deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - deploy-dev:
          requires:
            - build-and-test
          filters:
            branches:
              only: development
      - deploy-prod:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
