# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-and-test:
    docker:
      - image: docker:17.11.0-ce
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: docker-compose run test yarn test

  deploy-dev:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - run:
          name: Setup serverless configuration
          command: |
            export LAMBDA_ROLE="arn:aws:iam::168375318165:role/AWSLambdaBasicExecutionRole"
            yarn serverless config credentials --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY} --profile circle-ci-dev -o
      - run:
          name: Deploy to AWS development server with serverless
          command: yarn deploy --stage dev --conceal

  deploy-prod:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - run:
          name: Setup serverless configuration
          command: |
            export LAMBDA_ROLE="arn:aws:iam::168375318165:role/AWSLambdaBasicExecutionRole"
            yarn serverless config credentials --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY} --profile circle-ci-prod -o

      - run:
          name: Deploy to AWS production server with serverless
          command: yarn deploy --stage prod --conceal

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - deploy-dev:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - build-and-test
          filters:
            branches:
              only: development
