# Aliases
docker-defaults: &docker-defaults
  docker:
    - image: nyulibraries/circleci_docker:18.06.1-ce-git-compose-1.22.0
  working_directory: ~/app

auth_docker: &auth_docker
  run:
    name: Authenticate Docker
    command: |
      docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"

pull: &pull
  run:
    name: Pull docker images
    command: ./scripts/pull_docker.sh

push: &push
  run:
    name: Push docker images
    command: ./scripts/push_docker.sh

build: &build
  run:
    name: Build images
    command: docker-compose build

test: &test
  run:
    name: Test
    command: docker-compose run test

version: 2
jobs:
  deploy-staging-awsdev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *auth_docker
      - <<: *pull
      - <<: *build
      - <<: *push
      - <<: *test
      - run:
          name: Deploy via serverless to development account
          command: |
            REST_API_ID=$REST_API_ID_DEV \
            REST_API_NAMESPACE_RESOURCE_ID=$REST_API_NAMESPACE_RESOURCE_ID_DEV \
            REST_API_ROOT_RESOURCE_ID=$REST_API_ROOT_RESOURCE_ID_DEV \
            docker-compose run deploy yarn serverless deploy --stage=dev --region=$REGION
  deploy-staging-awsprod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *auth_docker
      - <<: *pull
      - <<: *build
      - <<: *push
      - <<: *test
      - run:
          name: Deploy via serverless to production account
          command: |
            REST_API_ID=$REST_API_ID_DEV \
            REST_API_NAMESPACE_RESOURCE_ID=$REST_API_NAMESPACE_RESOURCE_ID_DEV \
            REST_API_ROOT_RESOURCE_ID=$REST_API_ROOT_RESOURCE_ID_DEV \
            docker-compose run deploy yarn serverless deploy --stage=dev --region=$REGION

  deploy-production-awsdev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *auth_docker
      - <<: *pull
      - <<: *build
      - <<: *push
      - <<: *test
      - run:
          name: Deploy via serverless to development account
          command: |
            REST_API_ID=$REST_API_ID_PROD \
            REST_API_NAMESPACE_RESOURCE_ID=$REST_API_NAMESPACE_RESOURCE_ID_PROD \
            REST_API_ROOT_RESOURCE_ID=$REST_API_ROOT_RESOURCE_ID_PROD \
            docker-compose run deploy yarn serverless deploy --stage=prod --region=$REGION

  deploy-production-awsprod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *auth_docker
      - <<: *pull
      - <<: *build
      - <<: *push
      - <<: *test
      - run:
          name: Deploy via serverless to production account
          command: |
            REST_API_ID=$REST_API_ID_PROD \
            REST_API_NAMESPACE_RESOURCE_ID=$REST_API_NAMESPACE_RESOURCE_ID_PROD \
            REST_API_ROOT_RESOURCE_ID=$REST_API_ROOT_RESOURCE_ID_PROD \
            docker-compose run deploy yarn serverless deploy --stage=prod --region=$REGION

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy-staging-awsdev:
          context: web-lambdas-aws-nyulitsdev
          filters:
            branches:
              ignore: master
      - deploy-staging-awsprod:
          context: web-lambdas-aws-nyulits
          filters:
            branches:
              ignore: master
      - deploy-production-awsdev:
          context: web-lambdas-aws-nyulitsdev
          filters:
            branches:
              only: master
      - deploy-production-awsprod:
          context: web-lambdas-aws-nyulits
          filters:
            branches:
              only: master
